blog/urls.py
from django.urls import path
from django.urls import path
from .views import (
    BlogListView,
    BlogDetailView,
    LikeView,
    DisLikeView,
    BlogCreateView,
    EventListView,
    EventListDetailView,
    EventListCreateView,
)

# from .views import BlogListView, BlogDetailView, LikeView, DisLikeView, BlogCreateView

app_name = 'blog'

# urlpatterns = [
#     path('', BlogListView.as_view(), name='blog_list'),
#     path('create/', BlogCreateView.as_view(), name='blog_create'),  # Place this before <slug:slug>
#     path('<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
#     path('like_post/<int:pk>', LikeView, name='like_post'),
#     path('dislike_post/<int:pk>', DisLikeView, name='dislike_post'),
# ]

 

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('events/create/', EventListCreateView.as_view(), name='event_list_create'),
    path('events/', EventListView.as_view(), name='event_list'),
    path('events/<slug:slug>/', EventListDetailView.as_view(), name='event_list_detail'),
    path('<slug:event_slug>/create/', BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('like_post/<int:pk>', LikeView, name='like_post'),
    path('dislike_post/<int:pk>', DisLikeView, name='dislike_post'),
]

blog_project/urls.py
from django.urls import path, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # add this line
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class EventList(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:event_list_detail', args=[self.slug])
    
class Post(models.Model):
    image_post = models.ImageField(null=True, blank=True, upload_to='images/')
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    votes = models.IntegerField(default=0)
    event_list = models.ForeignKey(EventList, on_delete=models.CASCADE, related_name='posts')  # Associate posts with an event list

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[self.slug])

blog/views.py
from django.views.generic import ListView, DetailView
from .models import Post
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail

def LikeView(request, pk):
    selected_post = get_object_or_404(Post, id =request.POST.get('post_id')) # Get id of the pos
    selected_post.votes = 1 # increase votes for post_id
    selected_post.save() # save votes for post_id
    return HttpResponseRedirect(reverse('blog:blog_list'))

def DisLikeView(request, pk):
    selected_post = get_object_or_404(Post, id =request.POST.get('post_id_no'))
    selected_post.votes = -1
    selected_post.save()
    return HttpResponseRedirect(reverse('blog:blog_list'))

class BlogListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/blog_list.html'


class BlogDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/blog_detail.html'

from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import Post, EventList

# class BlogCreateView(CreateView):
#     model = Post
#     fields = ['title', 'body', 'slug', 'author']  # Specify fields for the form
#     template_name = 'blog/blog_form.html'
#     success_url = reverse_lazy('blog:blog_list')  # Redirect after successful creation

class BlogCreateView(CreateView):
    model = Post
    fields = ['title', 'body', 'slug', 'author']
    template_name = 'blog/blog_form.html'


    def form_valid(self, form):
        event_slug = self.kwargs.get('event_slug')  # Get the active EventList slug from URL
        event_list = get_object_or_404(EventList, slug=event_slug)  # Retrieve the EventList
        form.instance.event_list = event_list  # Automatically assign it
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.event_list.get_absolute_url()  # Redirect to event list page
    
class EventListView(ListView):
    model = EventList
    context_object_name = 'event_lists'
    template_name = 'blog/event_list.html'

class EventListDetailView(DetailView):
    model = EventList
    context_object_name = 'event_list'
    template_name = 'blog/event_list_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.object.posts.all()  # Get posts related to this event list
        return context

class EventListCreateView(CreateView):
    model = EventList
    fields = ['name', 'slug']  # Fields for the form
    template_name = 'blog/event_list_form.html'
    success_url = reverse_lazy('blog:event_list')  # Redirect back to event list after creation

templates/base.html
<!--templates/base.html-->

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>nema nazov</title>
</head>
<body>

<!--  header starts here-->
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:blog_list' %}">Pozvanky:) <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!--  header ends here-->

<!--main container starts here. It Is empty.-->
<div class="container my-4">
    {% block container %}
    {% endblock %}

</div>


<!-- jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

</body>
</html>

templates/blog/blog_detail.html
<!--templates/blog/blog_detail.html-->

{% extends 'base.html' %}

{% block container %}

<div class="row">
    <div class="card">
        <h5 class="card-header">{{ post.title }} by <span class="text-primary">{{ post.author }}</span></h5>
        <div class="card-body">
            <h5 class="card-title">Published: {{ post.publish }}</h5>
            <p class="card-text">{{ post.body }}</p>
        </div>
    </div>

</div>

{% endblock %}

templates/blog/blog_form.html
{% extends 'base.html' %}

{% block container %}
<h2>Create New Blog Post</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Submit</button>
</form>
<a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

templates/blog/blog_list.html
<!--templates/blog/blog_list.html-->

{% extends 'base.html' %}

{% block container %}

<div class="row">
    {% for post in posts %}
    {% if post.votes == 0 %}
    <div class="col-sm-6 mt-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.body | truncatechars:50 }}</p>
<div class="row">
<form action = "{% url 'blog:like_post' post.pk %}" method ="POST">
{% csrf_token %}
<button type = "submit", name = "post_id", value = "{{ post.id }}" class="btn btn-success">YES </button> 
</form>

<form action = "{% url 'blog:dislike_post' post.pk %}" method ="POST">
    {% csrf_token %}
    <button type = "submit", name = "post_id_no", value = "{{ post.id }}" class="btn btn-danger">NO</button> 
</form>
<a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read more</a>
</div>
</div>
</div>
</div>
    {% endif %}
    {% endfor %}

</div>

{% endblock %}

templates/blog/event_list.html
{% extends 'base.html' %}

{% block container %}
<h1>Event Lists</h1>

<div class="list-group">
    {% for event_list in event_lists %}
        <a href="{{ event_list.get_absolute_url }}" class="list-group-item list-group-item-action">
            {{ event_list.name }}
        </a>
    {% empty %}
        <p>No event lists available.</p>
    {% endfor %}
</div>

<!-- Button to create a new EventList -->
<a href="{% url 'blog:event_list_create' %}" class="btn btn-primary mt-3">Create New Event List</a>

{% endblock %}

templates/blog/event_list_detail.html
{% extends 'base.html' %}

{% block container %}

<h1>{{ event_list.name }}</h1>
 

<!--<div class="row">-->
<div class="col-sm-12 mt-6">
<div class="col-sm-6 mt-6">
<div class="card">
<a href="{% url 'blog:blog_create' %}" class="btn btn-primary mb-4">Create New Event</a>
</div>
</div>
    {% for post in posts %}
    <div class="col-sm-6 mt-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.body | truncatechars:50 }}</p>
<div class="row">
<form action = "{% url 'blog:like_post' post.pk %}" method ="POST">
{% csrf_token %}
<button type = "submit", name = "post_id", value = "{{ post.id }}" class="btn btn-success">YES </button> 
</form>

<form action = "{% url 'blog:dislike_post' post.pk %}" method ="POST">
    {% csrf_token %}
    <button type = "submit", name = "post_id_no", value = "{{ post.id }}" class="btn btn-danger">NO</button> 
</form>
<a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read more</a>
</div>
</div>
</div>
</div>
    {% endfor %}

</div>
 
{% endblock %}

templates/blog/event_list_form.html
{% extends 'base.html' %}

{% block container %}

<h1>{{ event_list.name }}</h1>
 

<!--<div class="row">-->
<div class="col-sm-12 mt-6">
<div class="col-sm-6 mt-6">
<div class="card">
<a href="{% url event_list.slug 'blog:blog_create'  %}" class="btn btn-primary mb-4">Create New Event</a>
</div>
</div>
    {% for post in posts %}
    <div class="col-sm-6 mt-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.body | truncatechars:50 }}</p>
<div class="row">
<form action = "{% url 'blog:like_post' post.pk %}" method ="POST">
{% csrf_token %}
<button type = "submit", name = "post_id", value = "{{ post.id }}" class="btn btn-success">YES </button> 
</form>

<form action = "{% url 'blog:dislike_post' post.pk %}" method ="POST">
    {% csrf_token %}
    <button type = "submit", name = "post_id_no", value = "{{ post.id }}" class="btn btn-danger">NO</button> 
</form>
<a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read more</a>
</div>
</div>
</div>
</div>
    {% endfor %}

</div>
 
{% endblock %}